# Generated by Django 4.1.4 on 2023-01-09 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
